# Generated by Django 6.0.3 on 2026-03-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название товара')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('category', models.CharField(choices=[('electronics', 'Электроника'), ('clothing', 'Одежда'), ('home', 'Дом и сад'), ('books', 'Книги'), ('toys', 'Игрушки'), ('sports', 'Спорт и отдых')], default='electronics', max_length=50, verbose_name='Категория')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(blank=True, verbose_name='Описание товара')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Бренд')),
                ('rating', models.FloatField(default=0, verbose_name='Рейтинг')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d/', verbose_name='Изображение товара')),
                ('status', models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0, verbose_name='Статус')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-time_create'],
                'indexes': [models.Index(fields=['-time_create'], name='queryrank_a_time_cr_927d12_idx'), models.Index(fields=['category'], name='queryrank_a_categor_2c29ce_idx'), models.Index(fields=['price'], name='queryrank_a_price_395a99_idx')],
            },
        ),
    ]
