# Generated by Django 6.0.3 on 2026-04-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryrank_app', '0004_remove_product_image_alter_product_cat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='products/photos/%Y/%m/%d/', verbose_name='Изображение товара'),
        ),
    ]
